### ISSUE TITLE
error related to the conf/swift.properties

### ISSUE THREAD

**Issue by JJguri** [JJguri/psimsV2#1]
An error appeared related to the conf/swift.properties file using the soft remotely. Similar to [this issue](https://github.com/RDCEP/psims/issues/10)

```
Exception in pysims:
    Arguments...
    Directory: psims-all-20210215-0539-7ajuoo69/jobs/q/pysims-qeoe0n2p
        exception @ swift-int.k, line: 530
Caused by: The executable .../test/prueba/run001/../../psims/pysims/pysims.py does not exist
        exception @ swift-int.k, line: 512
Caused by: Job failed with and exit code of 254
org.globus.cog.abstraction.impl.common.execution.JobException: Job failed with and exit code of 254 (exit code: -2)
        at org.globus.cog.abstraction.coaster.service.local.JobStatusHandler.requestComplete(JobStatusHandler.java:40)
        at org.globus.cog.coaster.handlers.RequestHandler.receiveCompleted(RequestHandler.java:88)
        at org.globus.cog.coaster.channels.AbstractCoasterChannel.handleRequest(AbstractCoasterChannel.java:536)
        at org.globus.cog.coaster.channels.AbstractStreamCoasterChannel.stepNIO(AbstractStreamCoasterChannel.java:238)
        at org.globus.cog.coaster.channels.NIOMultiplexer.loop(NIOMultiplexer.java:97)
        at org.globus.cog.coaster.channels.NIOMultiplexer.run(NIOMultiplexer.java:56)

Caused by: org.globus.cog.abstraction.impl.common.execution.JobException: Job failed with and exit code of 254
org.globus.cog.abstraction.impl.common.execution.JobException: Job failed with and exit code of 254 (exit code: -2)
        at org.globus.cog.abstraction.coaster.service.local.JobStatusHandler.requestComplete(JobStatusHandler.java:40)
        at org.globus.cog.coaster.handlers.RequestHandler.receiveCompleted(RequestHandler.java:88)
        at org.globus.cog.coaster.channels.AbstractCoasterChannel.handleRequest(AbstractCoasterChannel.java:536)
        at org.globus.cog.coaster.channels.AbstractStreamCoasterChannel.stepNIO(AbstractStreamCoasterChannel.java:238)
        at org.globus.cog.coaster.channels.NIOMultiplexer.loop(NIOMultiplexer.java:97)
        at org.globus.cog.coaster.channels.NIOMultiplexer.run(NIOMultiplexer.java:56)
(exit code: -16843010)

Execution failed:
e, line 44 not derived due to errors in data dependencies
        assignment @ psims-all, line: 47
Caused by: e, line 44 not derived due to errors in data dependencies
        at org.griphyn.vdl.karajan.lib.Mark.function(Mark.java:61)
        at org.griphyn.vdl.karajan.lib.SwiftFunction.runBody(SwiftFunction.java:110)
        at org.globus.cog.karajan.compiled.nodes.InternalFunction.run(InternalFunction.java:153)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.Catch.runBody(Catch.java:54)
        at org.globus.cog.karajan.compiled.nodes.InternalFunction.run(InternalFunction.java:153)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Try.run(Try.java:52)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.If.run(If.java:165)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.If.run(If.java:165)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.user.Function.runBody(Function.java:99)
        at org.globus.cog.karajan.compiled.nodes.user.InvocationWrapper.runBody(InvocationWrapper.java:246)
        at org.globus.cog.karajan.compiled.nodes.user.InvocationWrapper.run(InvocationWrapper.java:69)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.Sequential.run(Sequential.java:22)
        at org.globus.cog.karajan.compiled.nodes.user.Function.runBody(Function.java:99)
        at org.globus.cog.karajan.compiled.nodes.user.InvocationWrapper.runBody(InvocationWrapper.java:246)
        at org.globus.cog.karajan.compiled.nodes.user.InvocationWrapper.run(InvocationWrapper.java:69)
        at org.globus.cog.karajan.compiled.nodes.CompoundNode.runChild(CompoundNode.java:87)
        at org.globus.cog.karajan.compiled.nodes.UParallel$1.run(UParallel.java:68)
        at k.thr.LWThread.run(LWThread.java:228)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by JJguri** [comment]
the issue was that the run should be done specifically in the test folder. It is stated in some files related to the singularity container.
